server:
  port: 8081
spring:
  application:
    name: api-customer
  data:
    username: usr-customer-mongo
    password: pwd-customer-mongo
    database: customer-dev-mongo
    port: 27017
    host: localhost

urlCheck: http://localhost:8083

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/